language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopssmarksb
deply:
  api_key:
    secure: hXJmKo4XXc/sIW7zuaka+hBAorBYSio30doGpYnX4qOksRZq6hH1ft8BG5WJT3n1jtSyegMB9fpqzfuOrIKSuGuhMj0Vq0N/vAVzQL3upHrRz2Cx2ifPWMUJkPWV8YxaaZ8rFRGTCL9mV1jq4Ua4OjGD2QNr+MOlNVFq0NpYSS9jsAzWl+p0ST5JeNIAxSY6/iP6VTmyqz9dYeI+BbXoaUKvzG2LweKmMp468F+aymaO0p+0PiPCrqrSd6ggvqqdxYSc6IZuw9lw1EkF77zWKBv0NiVywokra/d/tWxFzOzI4f2v/r+CqN/8ST+NEqiLM38kcbeLLhImJDzk/+NeJhfmhAf1j72hYowHvTwxvNsh6WnbUjKSUo/k4BXcjw+BbL5qht8liL1cJhDgvOGSCAgHu1ZvLV1l5R1xKJZBNsk6GIk/eN/IhatBD8vdyztWISe+sgLiY69lODyvuzTYj9Hw/wK9b4lRqO92vHzSjs90uoMFIa0/Qo19eKN5B9B7fAwX4FnoxT/KQxygv6TUR9MMEHPxhmCUCKHvI9FAZAX06O9TQvW6xJgjbV377u76JLAXS7piLvHwn8QyLG9XBUaf8OgQ8Fxv+ykgcBQbiHSJwresBbbGfECyQ0vpDyFcYhGwyzm+eLO+jAKl0bdqQJ8unWHVB3z+dcOcKykBciI=
