language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopssmarksb
  api_key:
    secure: ok5OAvE2SJIOx+9PQZfHgUqB9BzCMYblKkX/DYI5/Ggy+xlXpbWFuBHt41dY64/O1MIoKha44fj9WCH/dgZ1Rlg/JzON9x7wIwuJ3yjZUQZPctZZjQDBMH3X+qpNw3QlTaQsp6+xFIR7FNRh2ecsjhtyAmCv8IDfyQxLbqb7NIhGgRnJT+wkjEnGFDYVGNw7L6icoTd9cjfWVwAxdF2TMxOAxSRMD+pkQhpHpIfHlh9NrmumVdFZkk334O8Rv95P9iOmabMtVOYz1sIux+WJFfVJ0nN7KuVOshEYDM7g+jJAU1Ar008bD2OOEnDM8t8B4OhYWgKIPQOKD/eJwa8gqL1cbbtVeHZtmnFswrSIr0hZxwLF6QpP6euZbmrrsiDe1hyr302reKLv4KeqtcaaqQK8MK+MOC/V3MM1iufV32gvYaOm6oH/YU+rDY51EYBO0FFUFsFRqSUZ4lBSbCWqkew88+uZjpAzGTv1Km5OM2DJ4xJjAeHheBbkjfzoYik2zlgagxDPIQljfkZ1sNestR1XygwM9LEg6WDHuZxVBmHl2rZLzKytt6FVbvRSgC57CoCBxHwZWTyYoQ/5IqC39lsCO75fRX+A1hkK+Avd233XUK1E49UZ+w0GB5SM8rd2GI2yX9XaBBFqM+bgx8vIMQNki7rbjnFnFHb9C8qjLPY=

