language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopssmarksb
  api_key:
    secure: ok5OAvE2SJIOx+9PQZfHgUqB9BzCMYblKkX/DYI5/Ggy+xlXpbWFuBHt41dY64/O1MIoKha44fj9WCH/dgZ1Rlg/JzON9x7wIwuJ3yjZUQZPctZZjQDBMH3X+qpNw3QlTaQsp6+xFIR7FNRh2ecsjhtyAmCv8IDfyQxLbqb7NIhGgRnJT+wkjEnGFDYVGNw7L6icoTd9cjfWVwAxdF2TMxOAxSRMD+pkQhpHpIfHlh9NrmumVdFZkk334O8Rv95P9iOmabMtVOYz1sIux+WJFfVJ0nN7KuVOshEYDM7g+jJAU1Ar008bD2OOEnDM8t8B4OhYWgKIPQOKD/eJwa8gqL1cbbtVeHZtmnFswrSIr0hZxwLF6QpP6euZbmrrsiDe1hyr302reKLv4KeqtcaaqQK8MK+MOC/V3MM1iufV32gvYaOm6oH/YU+rDY51EYBO0FFUFsFRqSUZ4lBSbCWqkew88+uZjpAzGTv1Km5OM2DJ4xJjAeHheBbkjfzoYik2zlgagxDPIQljfkZ1sNestR1XygwM9LEg6WDHuZxVBmHl2rZLzKytt6FVbvRSgC57CoCBxHwZWTyYoQ/5IqC39lsCO75fRX+A1hkK+Avd233XUK1E49UZ+w0GB5SM8rd2GI2yX9XaBBFqM+bgx8vIMQNki7rbjnFnFHb9C8qjLPY=
deply:
  api_key:
    secure: hXJmKo4XXc/sIW7zuaka+hBAorBYSio30doGpYnX4qOksRZq6hH1ft8BG5WJT3n1jtSyegMB9fpqzfuOrIKSuGuhMj0Vq0N/vAVzQL3upHrRz2Cx2ifPWMUJkPWV8YxaaZ8rFRGTCL9mV1jq4Ua4OjGD2QNr+MOlNVFq0NpYSS9jsAzWl+p0ST5JeNIAxSY6/iP6VTmyqz9dYeI+BbXoaUKvzG2LweKmMp468F+aymaO0p+0PiPCrqrSd6ggvqqdxYSc6IZuw9lw1EkF77zWKBv0NiVywokra/d/tWxFzOzI4f2v/r+CqN/8ST+NEqiLM38kcbeLLhImJDzk/+NeJhfmhAf1j72hYowHvTwxvNsh6WnbUjKSUo/k4BXcjw+BbL5qht8liL1cJhDgvOGSCAgHu1ZvLV1l5R1xKJZBNsk6GIk/eN/IhatBD8vdyztWISe+sgLiY69lODyvuzTYj9Hw/wK9b4lRqO92vHzSjs90uoMFIa0/Qo19eKN5B9B7fAwX4FnoxT/KQxygv6TUR9MMEHPxhmCUCKHvI9FAZAX06O9TQvW6xJgjbV377u76JLAXS7piLvHwn8QyLG9XBUaf8OgQ8Fxv+ykgcBQbiHSJwresBbbGfECyQ0vpDyFcYhGwyzm+eLO+jAKl0bdqQJ8unWHVB3z+dcOcKykBciI=
